# Generated by Django 3.2.9 on 2022-01-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clnt_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emails', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
