# Generated by Django 3.2.9 on 2022-02-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clnt_info',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
