# Generated by Django 3.2.9 on 2022-02-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apbook', '0002_alter_clnt_info_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('pimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
