# Generated by Django 3.2.9 on 2022-02-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apbook', '0003_uploadimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clnt_info',
            old_name='firsname',
            new_name='firstname',
        ),
    ]
