# Generated by Django 3.2.9 on 2022-02-15 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apbook', '0007_auto_20220203_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('Address', models.CharField(blank=True, default='', max_length=50)),
                ('phoneno', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apbook.clnt_info')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apbook.product')),
            ],
        ),
    ]
