# Generated by Django 3.2.9 on 2022-02-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apbook', '0009_rename_order_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
